# Generated by Django 6.0.5 on 2026-06-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_options_alter_ticketmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['name']},
        ),
    ]
