# Generated by Django 6.0.5 on 2026-05-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
