services:
  backend:
    build:
      context: ./ticketProject
    container_name: ticket-backend
    ports:
      - "8000:8000"
    volumes:
      - ./ticketProject:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./ticket-frontend
    container_name: ticket-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./ticket-frontend:/app
      - /app/node_modules
    depends_on:
      - backend